name: Auto Update Coop Data

on:
  schedule:
    - cron: '15 2,8,14,20 * * *' 
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright google-generativeai
          playwright install chromium

      - name: Run Scraper (AI Powered)
        env:
          # هنا نعطي السيرفر المفتاح من الخزنة
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scraper.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "تحديث الذكاء الاصطناعي لبيانات التدريب 🤖🚀"
          file_pattern: 'live_data.json'
